<?php

/**
 * FeeChargeCapInner1
 *
 * PHP version 8.1.1
 *
 * @category Class
 * @package  OpenAPI\Server\Model
 * @author   OpenAPI Generator team
 * @link     https://github.com/openapitools/openapi-generator
 */

/**
 * Account and Transaction API Specification
 *
 * Swagger for Account and Transaction API Specification
 *
 * The version of the OpenAPI document: 3.1.11
 * Contact: ServiceDesk@openbanking.org.uk
 * Generated by: https://github.com/openapitools/openapi-generator.git
 *
 */

/**
 * NOTE: This class is auto generated by the openapi generator program.
 * https://github.com/openapitools/openapi-generator
 * Do not edit the class manually.
 */

namespace OpenAPI\Server\Model;

use Symfony\Component\Validator\Constraints as Assert;
use JMS\Serializer\Annotation\Type;
use JMS\Serializer\Annotation\SerializedName;

/**
 * Class representing the FeeChargeCapInner1 model.
 *
 * Details about any caps (maximum charges) that apply to a particular fee/charge
 *
 * @package OpenAPI\Server\Model
 * @author  OpenAPI Generator team
 */

class FeeChargeCapInner1 extends FeeChargeCapInner
{
    /**
     * Fee/charge type which is being capped
     *
     * @var array|null
     * @SerializedName("FeeType")
     * @Assert\NotNull()
     * @Assert\All({
     *   @Assert\Choice({ "ServiceCAccountFee", "ServiceCAccountFeeMonthly", "ServiceCOther", "Other" })
     * })
     * @Assert\All({
     *   @Assert\Type("string")
     * })
     * @Type("array<string>")
     * @Assert\Count(
     *   min = 1
     * )
     */
    protected ?array $feeType = null;




    /**
     * Period e.g. day, week, month etc. for which the fee/charge is capped
     *
     * @var string|null
     * @SerializedName("CappingPeriod")
     * @Assert\Choice({ "AcademicTerm", "Day", "Half Year", "Month", "Quarter", "Week", "Year" })
     * @Assert\Type("string")
     * @Type("string")
     */
    protected ?string $cappingPeriod = null;
}
