<?php

/**
 * OBActiveOrHistoricCurrencyAndAmount8
 *
 * PHP version 8.1.1
 *
 * @category Class
 * @package  OpenAPI\Server\Model
 * @author   OpenAPI Generator team
 * @link     https://github.com/openapitools/openapi-generator
 */

/**
 * Account and Transaction API Specification
 *
 * Swagger for Account and Transaction API Specification
 *
 * The version of the OpenAPI document: 3.1.11
 * Contact: ServiceDesk@openbanking.org.uk
 * Generated by: https://github.com/openapitools/openapi-generator.git
 *
 */

/**
 * NOTE: This class is auto generated by the openapi generator program.
 * https://github.com/openapitools/openapi-generator
 * Do not edit the class manually.
 */

namespace OpenAPI\Server\Model;

/**
 * Class representing the OBActiveOrHistoricCurrencyAndAmount8 model.
 *
 * Amount of money associated with the amount type.
 *
 * @package OpenAPI\Server\Model
 * @author  OpenAPI Generator team
 */

class OBActiveOrHistoricCurrencyAndAmount8 extends OBActiveOrHistoricCurrencyAndAmount0
{
}
