<?php
/**
 * OBBalanceType1Code
 *
 * PHP version 8.1.1
 *
 * @category Class
 * @package  OpenAPI\Server\Model
 * @author   OpenAPI Generator team
 * @link     https://github.com/openapitools/openapi-generator
 */

/**
 * Account and Transaction API Specification
 *
 * Swagger for Account and Transaction API Specification
 *
 * The version of the OpenAPI document: 3.1.11
 * Contact: ServiceDesk@openbanking.org.uk
 * Generated by: https://github.com/openapitools/openapi-generator.git
 *
 */

/**
 * NOTE: This class is auto generated by the openapi generator program.
 * https://github.com/openapitools/openapi-generator
 * Do not edit the class manually.
 */

namespace OpenAPI\Server\Model;

use Symfony\Component\Validator\Constraints as Assert;
use JMS\Serializer\Annotation\Type;
use JMS\Serializer\Annotation\SerializedName;

/**
 * Class representing the OBBalanceType1Code model.
 *
 * Balance type, in a coded form.
 *
 * @package OpenAPI\Server\Model
 * @author  OpenAPI Generator team
 */
class OBBalanceType1Code
{
    /**
     * Possible values of this enum
     */
    const CLOSING_AVAILABLE = "ClosingAvailable";
    const CLOSING_BOOKED = "ClosingBooked";
    const CLOSING_CLEARED = "ClosingCleared";
    const EXPECTED = "Expected";
    const FORWARD_AVAILABLE = "ForwardAvailable";
    const INFORMATION = "Information";
    const INTERIM_AVAILABLE = "InterimAvailable";
    const INTERIM_BOOKED = "InterimBooked";
    const INTERIM_CLEARED = "InterimCleared";
    const OPENING_AVAILABLE = "OpeningAvailable";
    const OPENING_BOOKED = "OpeningBooked";
    const OPENING_CLEARED = "OpeningCleared";
    const PREVIOUSLY_CLOSED_BOOKED = "PreviouslyClosedBooked";
    
    /**
     * Gets allowable values of the enum
     * @return string[]
     */
    public static function getAllowableEnumValues()
    {
        return [
            self::CLOSING_AVAILABLE,
            self::CLOSING_BOOKED,
            self::CLOSING_CLEARED,
            self::EXPECTED,
            self::FORWARD_AVAILABLE,
            self::INFORMATION,
            self::INTERIM_AVAILABLE,
            self::INTERIM_BOOKED,
            self::INTERIM_CLEARED,
            self::OPENING_AVAILABLE,
            self::OPENING_BOOKED,
            self::OPENING_CLEARED,
            self::PREVIOUSLY_CLOSED_BOOKED,
        ];
    }
}



