<?php

/**
 * OBBranchAndFinancialInstitutionIdentification60
 *
 * PHP version 8.1.1
 *
 * @category Class
 * @package  OpenAPI\Server\Model
 * @author   OpenAPI Generator team
 * @link     https://github.com/openapitools/openapi-generator
 */

/**
 * Account and Transaction API Specification
 *
 * Swagger for Account and Transaction API Specification
 *
 * The version of the OpenAPI document: 3.1.11
 * Contact: ServiceDesk@openbanking.org.uk
 * Generated by: https://github.com/openapitools/openapi-generator.git
 *
 */

/**
 * NOTE: This class is auto generated by the openapi generator program.
 * https://github.com/openapitools/openapi-generator
 * Do not edit the class manually.
 */

namespace OpenAPI\Server\Model;

use Symfony\Component\Validator\Constraints as Assert;
use JMS\Serializer\Annotation\Type;
use JMS\Serializer\Annotation\SerializedName;

/**
 * Class representing the OBBranchAndFinancialInstitutionIdentification60 model.
 *
 * Party that manages the account on behalf of the account owner, that is manages the registration and booking of entries on the account, calculates balances on the account and provides information about the account. This is the servicer of the beneficiary account.
 *
 * @package OpenAPI\Server\Model
 * @author  OpenAPI Generator team
 */

class OBBranchAndFinancialInstitutionIdentification60
{
    /**
     * Name of the identification scheme, in a coded form as published in an external list.
     *
     * @var string|null
     * @SerializedName("SchemeName")
     * @Assert\Type("string")
     * @Type("string")
     */
    protected ?string $schemeName = null;

    /**
     * Unique and unambiguous identification of the servicing institution.
     *
     * @var string|null
     * @SerializedName("Identification")
     * @Assert\Type("string")
     * @Type("string")
     * @Assert\Length(
     *   max = 35
     * )
     * @Assert\Length(
     *   min = 1
     * )
     */
    protected ?string $identification = null;

    /**
     * Name by which an agent is known and which is usually used to identify that agent.
     *
     * @var string|null
     * @SerializedName("Name")
     * @Assert\Type("string")
     * @Type("string")
     * @Assert\Length(
     *   max = 140
     * )
     * @Assert\Length(
     *   min = 1
     * )
     */
    protected ?string $name = null;

    /**
     * @var OBPostalAddress6|null
     * @SerializedName("PostalAddress")
     * @Assert\Type("OpenAPI\Server\Model\OBPostalAddress6")
     * @Type("OpenAPI\Server\Model\OBPostalAddress6")
     */
    protected ?OBPostalAddress6 $postalAddress = null;

    /**
     * Constructor
     * @param array|null $data Associated array of property values initializing the model
     */
    public function __construct(array $data = null)
    {
        $this->schemeName = $data['schemeName'] ?? null;
        $this->identification = $data['identification'] ?? null;
        $this->name = $data['name'] ?? null;
        $this->postalAddress = $data['postalAddress'] ?? null;
    }

    /**
     * Gets schemeName.
     *
     * @return string|null
     */
    public function getSchemeName(): ?string
    {
        return $this->schemeName;
    }

    /**
     * Sets schemeName.
     *
     * @param string|null $schemeName  Name of the identification scheme, in a coded form as published in an external list.
     *
     * @return $this
     */
    public function setSchemeName(?string $schemeName = null): self
    {
        $this->schemeName = $schemeName;

        return $this;
    }

    /**
     * Gets identification.
     *
     * @return string|null
     */
    public function getIdentification(): ?string
    {
        return $this->identification;
    }

    /**
     * Sets identification.
     *
     * @param string|null $identification  Unique and unambiguous identification of the servicing institution.
     *
     * @return $this
     */
    public function setIdentification(?string $identification = null): self
    {
        $this->identification = $identification;

        return $this;
    }

    /**
     * Gets name.
     *
     * @return string|null
     */
    public function getName(): ?string
    {
        return $this->name;
    }

    /**
     * Sets name.
     *
     * @param string|null $name  Name by which an agent is known and which is usually used to identify that agent.
     *
     * @return $this
     */
    public function setName(?string $name = null): self
    {
        $this->name = $name;

        return $this;
    }

    /**
     * Gets postalAddress.
     *
     * @return OBPostalAddress6|null
     */
    public function getPostalAddress(): ?OBPostalAddress6
    {
        return $this->postalAddress;
    }

    /**
     * Sets postalAddress.
     *
     * @param OBPostalAddress6|null $postalAddress
     *
     * @return $this
     */
    public function setPostalAddress(?OBPostalAddress6 $postalAddress = null): self
    {
        $this->postalAddress = $postalAddress;

        return $this;
    }
}
