<?php
/**
 * OBPCAData1
 *
 * PHP version 8.1.1
 *
 * @category Class
 * @package  OpenAPI\Server\Model
 * @author   OpenAPI Generator team
 * @link     https://github.com/openapitools/openapi-generator
 */

/**
 * Account and Transaction API Specification
 *
 * Swagger for Account and Transaction API Specification
 *
 * The version of the OpenAPI document: 3.1.11
 * Contact: ServiceDesk@openbanking.org.uk
 * Generated by: https://github.com/openapitools/openapi-generator.git
 *
 */

/**
 * NOTE: This class is auto generated by the openapi generator program.
 * https://github.com/openapitools/openapi-generator
 * Do not edit the class manually.
 */

namespace OpenAPI\Server\Model;

use Symfony\Component\Validator\Constraints as Assert;
use JMS\Serializer\Annotation\Type;
use JMS\Serializer\Annotation\SerializedName;

/**
 * Class representing the OBPCAData1 model.
 *
 * @package OpenAPI\Server\Model
 * @author  OpenAPI Generator team
 */

class OBPCAData1 
{
        /**
     * @var ProductDetails1|null
     * @SerializedName("ProductDetails")
     * @Assert\Type("OpenAPI\Server\Model\ProductDetails1")
     * @Type("OpenAPI\Server\Model\ProductDetails1")
     */
    protected ?ProductDetails1 $productDetails = null;

    /**
     * @var CreditInterest1|null
     * @SerializedName("CreditInterest")
     * @Assert\Type("OpenAPI\Server\Model\CreditInterest1")
     * @Type("OpenAPI\Server\Model\CreditInterest1")
     */
    protected ?CreditInterest1 $creditInterest = null;

    /**
     * @var Overdraft1|null
     * @SerializedName("Overdraft")
     * @Assert\Type("OpenAPI\Server\Model\Overdraft1")
     * @Type("OpenAPI\Server\Model\Overdraft1")
     */
    protected ?Overdraft1 $overdraft = null;

    /**
     * @var OtherFeesCharges|null
     * @SerializedName("OtherFeesCharges")
     * @Assert\Type("OpenAPI\Server\Model\OtherFeesCharges")
     * @Type("OpenAPI\Server\Model\OtherFeesCharges")
     */
    protected ?OtherFeesCharges $otherFeesCharges = null;

    /**
     * Constructor
     * @param array|null $data Associated array of property values initializing the model
     */
    public function __construct(array $data = null)
    {
        $this->productDetails = $data['productDetails'] ?? null;
        $this->creditInterest = $data['creditInterest'] ?? null;
        $this->overdraft = $data['overdraft'] ?? null;
        $this->otherFeesCharges = $data['otherFeesCharges'] ?? null;
    }

    /**
     * Gets productDetails.
     *
     * @return ProductDetails1|null
     */
    public function getProductDetails(): ?ProductDetails1
    {
        return $this->productDetails;
    }

    /**
     * Sets productDetails.
     *
     * @param ProductDetails1|null $productDetails
     *
     * @return $this
     */
    public function setProductDetails(?ProductDetails1 $productDetails = null): self
    {
        $this->productDetails = $productDetails;

        return $this;
    }

    /**
     * Gets creditInterest.
     *
     * @return CreditInterest1|null
     */
    public function getCreditInterest(): ?CreditInterest1
    {
        return $this->creditInterest;
    }

    /**
     * Sets creditInterest.
     *
     * @param CreditInterest1|null $creditInterest
     *
     * @return $this
     */
    public function setCreditInterest(?CreditInterest1 $creditInterest = null): self
    {
        $this->creditInterest = $creditInterest;

        return $this;
    }

    /**
     * Gets overdraft.
     *
     * @return Overdraft1|null
     */
    public function getOverdraft(): ?Overdraft1
    {
        return $this->overdraft;
    }

    /**
     * Sets overdraft.
     *
     * @param Overdraft1|null $overdraft
     *
     * @return $this
     */
    public function setOverdraft(?Overdraft1 $overdraft = null): self
    {
        $this->overdraft = $overdraft;

        return $this;
    }

    /**
     * Gets otherFeesCharges.
     *
     * @return OtherFeesCharges|null
     */
    public function getOtherFeesCharges(): ?OtherFeesCharges
    {
        return $this->otherFeesCharges;
    }

    /**
     * Sets otherFeesCharges.
     *
     * @param OtherFeesCharges|null $otherFeesCharges
     *
     * @return $this
     */
    public function setOtherFeesCharges(?OtherFeesCharges $otherFeesCharges = null): self
    {
        $this->otherFeesCharges = $otherFeesCharges;

        return $this;
    }
}


