<?php
/**
 * OBReadStandingOrder6Data
 *
 * PHP version 8.1.1
 *
 * @category Class
 * @package  OpenAPI\Server\Model
 * @author   OpenAPI Generator team
 * @link     https://github.com/openapitools/openapi-generator
 */

/**
 * Account and Transaction API Specification
 *
 * Swagger for Account and Transaction API Specification
 *
 * The version of the OpenAPI document: 3.1.11
 * Contact: ServiceDesk@openbanking.org.uk
 * Generated by: https://github.com/openapitools/openapi-generator.git
 *
 */

/**
 * NOTE: This class is auto generated by the openapi generator program.
 * https://github.com/openapitools/openapi-generator
 * Do not edit the class manually.
 */

namespace OpenAPI\Server\Model;

use Symfony\Component\Validator\Constraints as Assert;
use JMS\Serializer\Annotation\Type;
use JMS\Serializer\Annotation\SerializedName;

/**
 * Class representing the OBReadStandingOrder6Data model.
 *
 * @package OpenAPI\Server\Model
 * @author  OpenAPI Generator team
 */

class OBReadStandingOrder6Data 
{
        /**
     * @var array|null
     * @SerializedName("StandingOrder")
     * @Assert\All({
     *   @Assert\Type("OpenAPI\Server\Model\OBStandingOrder6")
     * })
     * @Type("array<OpenAPI\Server\Model\OBStandingOrder6>")
     */
    protected ?array $standingOrder = null;

    /**
     * Constructor
     * @param array|null $data Associated array of property values initializing the model
     */
    public function __construct(array $data = null)
    {
        $this->standingOrder = $data['standingOrder'] ?? null;
    }

    /**
     * Gets standingOrder.
     *
     * @return array|null
     */
    public function getStandingOrder(): ?array
    {
        return $this->standingOrder;
    }

    /**
     * Sets standingOrder.
     *
     * @param array|null $standingOrder
     *
     * @return $this
     */
    public function setStandingOrder(?array $standingOrder = null): self
    {
        $this->standingOrder = $standingOrder;

        return $this;
    }
}


