<?php
/**
 * OBReadBeneficiary5Data
 *
 * PHP version 8.1.1
 *
 * @category Class
 * @package  OpenAPI\Server\Model
 * @author   OpenAPI Generator team
 * @link     https://github.com/openapitools/openapi-generator
 */

/**
 * Account and Transaction API Specification
 *
 * Swagger for Account and Transaction API Specification
 *
 * The version of the OpenAPI document: 3.1.11
 * Contact: ServiceDesk@openbanking.org.uk
 * Generated by: https://github.com/openapitools/openapi-generator.git
 *
 */

/**
 * NOTE: This class is auto generated by the openapi generator program.
 * https://github.com/openapitools/openapi-generator
 * Do not edit the class manually.
 */

namespace OpenAPI\Server\Model;

use Symfony\Component\Validator\Constraints as Assert;
use JMS\Serializer\Annotation\Type;
use JMS\Serializer\Annotation\SerializedName;

/**
 * Class representing the OBReadBeneficiary5Data model.
 *
 * @package OpenAPI\Server\Model
 * @author  OpenAPI Generator team
 */

class OBReadBeneficiary5Data 
{
        /**
     * @var array|null
     * @SerializedName("Beneficiary")
     * @Assert\All({
     *   @Assert\Type("OpenAPI\Server\Model\OBBeneficiary5")
     * })
     * @Type("array<OpenAPI\Server\Model\OBBeneficiary5>")
     */
    protected ?array $beneficiary = null;

    /**
     * Constructor
     * @param array|null $data Associated array of property values initializing the model
     */
    public function __construct(array $data = null)
    {
        $this->beneficiary = $data['beneficiary'] ?? null;
    }

    /**
     * Gets beneficiary.
     *
     * @return array|null
     */
    public function getBeneficiary(): ?array
    {
        return $this->beneficiary;
    }

    /**
     * Sets beneficiary.
     *
     * @param array|null $beneficiary
     *
     * @return $this
     */
    public function setBeneficiary(?array $beneficiary = null): self
    {
        $this->beneficiary = $beneficiary;

        return $this;
    }
}


