<?php
/**
 * OBReadProduct2DataProductInnerOtherProductTypeRepaymentRepaymentHolidayInner
 *
 * PHP version 8.1.1
 *
 * @category Class
 * @package  OpenAPI\Server\Model
 * @author   OpenAPI Generator team
 * @link     https://github.com/openapitools/openapi-generator
 */

/**
 * Account and Transaction API Specification
 *
 * Swagger for Account and Transaction API Specification
 *
 * The version of the OpenAPI document: 3.1.11
 * Contact: ServiceDesk@openbanking.org.uk
 * Generated by: https://github.com/openapitools/openapi-generator.git
 *
 */

/**
 * NOTE: This class is auto generated by the openapi generator program.
 * https://github.com/openapitools/openapi-generator
 * Do not edit the class manually.
 */

namespace OpenAPI\Server\Model;

use Symfony\Component\Validator\Constraints as Assert;
use JMS\Serializer\Annotation\Type;
use JMS\Serializer\Annotation\SerializedName;

/**
 * Class representing the OBReadProduct2DataProductInnerOtherProductTypeRepaymentRepaymentHolidayInner model.
 *
 * Details of capital repayment holiday if any
 *
 * @package OpenAPI\Server\Model
 * @author  OpenAPI Generator team
 */

class OBReadProduct2DataProductInnerOtherProductTypeRepaymentRepaymentHolidayInner 
{
        /**
     * The maximum length/duration of a Repayment Holiday
     *
     * @var int|null
     * @SerializedName("MaxHolidayLength")
     * @Assert\Type("int")
     * @Type("int")
     */
    protected ?int $maxHolidayLength = null;

    /**
     * The unit of period (days, weeks, months etc.) of the repayment holiday
     *
     * @var string|null
     * @SerializedName("MaxHolidayPeriod")
     * @Assert\Choice({ "PACT", "PDAY", "PHYR", "PMTH", "PQTR", "PWEK", "PYER" })
     * @Assert\Type("string")
     * @Type("string")
     */
    protected ?string $maxHolidayPeriod = null;

    /**
     * @var array|null
     * @SerializedName("Notes")
     * @Assert\All({
     *   @Assert\Type("string")
     * })
     * @Type("array<string>")
     */
    protected ?array $notes = null;

    /**
     * Constructor
     * @param array|null $data Associated array of property values initializing the model
     */
    public function __construct(array $data = null)
    {
        $this->maxHolidayLength = $data['maxHolidayLength'] ?? null;
        $this->maxHolidayPeriod = $data['maxHolidayPeriod'] ?? null;
        $this->notes = $data['notes'] ?? null;
    }

    /**
     * Gets maxHolidayLength.
     *
     * @return int|null
     */
    public function getMaxHolidayLength(): ?int
    {
        return $this->maxHolidayLength;
    }

    /**
     * Sets maxHolidayLength.
     *
     * @param int|null $maxHolidayLength  The maximum length/duration of a Repayment Holiday
     *
     * @return $this
     */
    public function setMaxHolidayLength(?int $maxHolidayLength = null): self
    {
        $this->maxHolidayLength = $maxHolidayLength;

        return $this;
    }

    /**
     * Gets maxHolidayPeriod.
     *
     * @return string|null
     */
    public function getMaxHolidayPeriod(): ?string
    {
        return $this->maxHolidayPeriod;
    }

    /**
     * Sets maxHolidayPeriod.
     *
     * @param string|null $maxHolidayPeriod  The unit of period (days, weeks, months etc.) of the repayment holiday
     *
     * @return $this
     */
    public function setMaxHolidayPeriod(?string $maxHolidayPeriod = null): self
    {
        $this->maxHolidayPeriod = $maxHolidayPeriod;

        return $this;
    }

    /**
     * Gets notes.
     *
     * @return array|null
     */
    public function getNotes(): ?array
    {
        return $this->notes;
    }

    /**
     * Sets notes.
     *
     * @param array|null $notes
     *
     * @return $this
     */
    public function setNotes(?array $notes = null): self
    {
        $this->notes = $notes;

        return $this;
    }
}


