<?php
/**
 * OBReadProduct2DataProductInnerOtherProductTypeProductDetails
 *
 * PHP version 8.1.1
 *
 * @category Class
 * @package  OpenAPI\Server\Model
 * @author   OpenAPI Generator team
 * @link     https://github.com/openapitools/openapi-generator
 */

/**
 * Account and Transaction API Specification
 *
 * Swagger for Account and Transaction API Specification
 *
 * The version of the OpenAPI document: 3.1.11
 * Contact: ServiceDesk@openbanking.org.uk
 * Generated by: https://github.com/openapitools/openapi-generator.git
 *
 */

/**
 * NOTE: This class is auto generated by the openapi generator program.
 * https://github.com/openapitools/openapi-generator
 * Do not edit the class manually.
 */

namespace OpenAPI\Server\Model;

use Symfony\Component\Validator\Constraints as Assert;
use JMS\Serializer\Annotation\Type;
use JMS\Serializer\Annotation\SerializedName;

/**
 * Class representing the OBReadProduct2DataProductInnerOtherProductTypeProductDetails model.
 *
 * @package OpenAPI\Server\Model
 * @author  OpenAPI Generator team
 */

class OBReadProduct2DataProductInnerOtherProductTypeProductDetails 
{
        /**
     * @var array|null
     * @SerializedName("Segment")
     * @Assert\All({
     *   @Assert\Choice({ "GEAS", "GEBA", "GEBR", "GEBU", "GECI", "GECS", "GEFB", "GEFG", "GEG", "GEGR", "GEGS", "GEOT", "GEOV", "GEPA", "GEPR", "GERE", "GEST", "GEYA", "GEYO", "PSCA", "PSES", "PSNC", "PSNP", "PSRG", "PSSS", "PSST", "PSSW" })
     * })
     * @Assert\All({
     *   @Assert\Type("string")
     * })
     * @Type("array<string>")
     */
    protected ?array $segment = null;

    /**
     * The length/duration of the fee free period
     *
     * @var int|null
     * @SerializedName("FeeFreeLength")
     * @Assert\Type("int")
     * @Type("int")
     */
    protected ?int $feeFreeLength = null;

    /**
     * The unit of period (days, weeks, months etc.) of the promotional length
     *
     * @var string|null
     * @SerializedName("FeeFreeLengthPeriod")
     * @Assert\Choice({ "PACT", "PDAY", "PHYR", "PMTH", "PQTR", "PWEK", "PYER" })
     * @Assert\Type("string")
     * @Type("string")
     */
    protected ?string $feeFreeLengthPeriod = null;

    /**
     * The maximum relevant charges that could accrue as defined fully in Part 7 of the CMA order
     *
     * @var string|null
     * @SerializedName("MonthlyMaximumCharge")
     * @Assert\Type("string")
     * @Type("string")
     * @Assert\Regex("/^(-?\\d{1,14}){1}(\\.\\d{1,4}){0,1}$/")
     */
    protected ?string $monthlyMaximumCharge = null;

    /**
     * @var array|null
     * @SerializedName("Notes")
     * @Assert\All({
     *   @Assert\Type("string")
     * })
     * @Type("array<string>")
     */
    protected ?array $notes = null;

    /**
     * @var OBOtherCodeType10|null
     * @SerializedName("OtherSegment")
     * @Assert\Type("OpenAPI\Server\Model\OBOtherCodeType10")
     * @Type("OpenAPI\Server\Model\OBOtherCodeType10")
     */
    protected ?OBOtherCodeType10 $otherSegment = null;

    /**
     * Constructor
     * @param array|null $data Associated array of property values initializing the model
     */
    public function __construct(array $data = null)
    {
        $this->segment = $data['segment'] ?? null;
        $this->feeFreeLength = $data['feeFreeLength'] ?? null;
        $this->feeFreeLengthPeriod = $data['feeFreeLengthPeriod'] ?? null;
        $this->monthlyMaximumCharge = $data['monthlyMaximumCharge'] ?? null;
        $this->notes = $data['notes'] ?? null;
        $this->otherSegment = $data['otherSegment'] ?? null;
    }

    /**
     * Gets segment.
     *
     * @return array|null
     */
    public function getSegment(): ?array
    {
        return $this->segment;
    }

    /**
     * Sets segment.
     *
     * @param array|null $segment
     *
     * @return $this
     */
    public function setSegment(?array $segment = null): self
    {
        $this->segment = $segment;

        return $this;
    }

    /**
     * Gets feeFreeLength.
     *
     * @return int|null
     */
    public function getFeeFreeLength(): ?int
    {
        return $this->feeFreeLength;
    }

    /**
     * Sets feeFreeLength.
     *
     * @param int|null $feeFreeLength  The length/duration of the fee free period
     *
     * @return $this
     */
    public function setFeeFreeLength(?int $feeFreeLength = null): self
    {
        $this->feeFreeLength = $feeFreeLength;

        return $this;
    }

    /**
     * Gets feeFreeLengthPeriod.
     *
     * @return string|null
     */
    public function getFeeFreeLengthPeriod(): ?string
    {
        return $this->feeFreeLengthPeriod;
    }

    /**
     * Sets feeFreeLengthPeriod.
     *
     * @param string|null $feeFreeLengthPeriod  The unit of period (days, weeks, months etc.) of the promotional length
     *
     * @return $this
     */
    public function setFeeFreeLengthPeriod(?string $feeFreeLengthPeriod = null): self
    {
        $this->feeFreeLengthPeriod = $feeFreeLengthPeriod;

        return $this;
    }

    /**
     * Gets monthlyMaximumCharge.
     *
     * @return string|null
     */
    public function getMonthlyMaximumCharge(): ?string
    {
        return $this->monthlyMaximumCharge;
    }

    /**
     * Sets monthlyMaximumCharge.
     *
     * @param string|null $monthlyMaximumCharge  The maximum relevant charges that could accrue as defined fully in Part 7 of the CMA order
     *
     * @return $this
     */
    public function setMonthlyMaximumCharge(?string $monthlyMaximumCharge = null): self
    {
        $this->monthlyMaximumCharge = $monthlyMaximumCharge;

        return $this;
    }

    /**
     * Gets notes.
     *
     * @return array|null
     */
    public function getNotes(): ?array
    {
        return $this->notes;
    }

    /**
     * Sets notes.
     *
     * @param array|null $notes
     *
     * @return $this
     */
    public function setNotes(?array $notes = null): self
    {
        $this->notes = $notes;

        return $this;
    }

    /**
     * Gets otherSegment.
     *
     * @return OBOtherCodeType10|null
     */
    public function getOtherSegment(): ?OBOtherCodeType10
    {
        return $this->otherSegment;
    }

    /**
     * Sets otherSegment.
     *
     * @param OBOtherCodeType10|null $otherSegment
     *
     * @return $this
     */
    public function setOtherSegment(?OBOtherCodeType10 $otherSegment = null): self
    {
        $this->otherSegment = $otherSegment;

        return $this;
    }
}


