<?php
/**
 * OBReadAccount6Data
 *
 * PHP version 8.1.1
 *
 * @category Class
 * @package  OpenAPI\Server\Model
 * @author   OpenAPI Generator team
 * @link     https://github.com/openapitools/openapi-generator
 */

/**
 * Account and Transaction API Specification
 *
 * Swagger for Account and Transaction API Specification
 *
 * The version of the OpenAPI document: 3.1.11
 * Contact: ServiceDesk@openbanking.org.uk
 * Generated by: https://github.com/openapitools/openapi-generator.git
 *
 */

/**
 * NOTE: This class is auto generated by the openapi generator program.
 * https://github.com/openapitools/openapi-generator
 * Do not edit the class manually.
 */

namespace OpenAPI\Server\Model;

use Symfony\Component\Validator\Constraints as Assert;
use JMS\Serializer\Annotation\Type;
use JMS\Serializer\Annotation\SerializedName;

/**
 * Class representing the OBReadAccount6Data model.
 *
 * @package OpenAPI\Server\Model
 * @author  OpenAPI Generator team
 */

class OBReadAccount6Data 
{
        /**
     * @var array|null
     * @SerializedName("Account")
     * @Assert\All({
     *   @Assert\Type("OpenAPI\Server\Model\OBAccount6")
     * })
     * @Type("array<OpenAPI\Server\Model\OBAccount6>")
     */
    protected ?array $account = null;

    /**
     * Constructor
     * @param array|null $data Associated array of property values initializing the model
     */
    public function __construct(array $data = null)
    {
        $this->account = $data['account'] ?? null;
    }

    /**
     * Gets account.
     *
     * @return array|null
     */
    public function getAccount(): ?array
    {
        return $this->account;
    }

    /**
     * Sets account.
     *
     * @param array|null $account
     *
     * @return $this
     */
    public function setAccount(?array $account = null): self
    {
        $this->account = $account;

        return $this;
    }
}


