<?php
/**
 * OBStatement2DetailStatementAmountInner
 *
 * PHP version 8.1.1
 *
 * @category Class
 * @package  OpenAPI\Server\Model
 * @author   OpenAPI Generator team
 * @link     https://github.com/openapitools/openapi-generator
 */

/**
 * Account and Transaction API Specification
 *
 * Swagger for Account and Transaction API Specification
 *
 * The version of the OpenAPI document: 3.1.11
 * Contact: ServiceDesk@openbanking.org.uk
 * Generated by: https://github.com/openapitools/openapi-generator.git
 *
 */

/**
 * NOTE: This class is auto generated by the openapi generator program.
 * https://github.com/openapitools/openapi-generator
 * Do not edit the class manually.
 */

namespace OpenAPI\Server\Model;

use Symfony\Component\Validator\Constraints as Assert;
use JMS\Serializer\Annotation\Type;
use JMS\Serializer\Annotation\SerializedName;

/**
 * Class representing the OBStatement2DetailStatementAmountInner model.
 *
 * Set of elements used to provide details of a generic amount for the statement resource.
 *
 * @package OpenAPI\Server\Model
 * @author  OpenAPI Generator team
 */

class OBStatement2DetailStatementAmountInner 
{
        /**
     * @var OBCreditDebitCode0|null
     * @SerializedName("CreditDebitIndicator")
     * @Assert\NotNull()
     * @Assert\Valid()
     * @Assert\Type("OpenAPI\Server\Model\OBCreditDebitCode0")
     * @Type("OpenAPI\Server\Model\OBCreditDebitCode0")
     */
    protected ?OBCreditDebitCode0 $creditDebitIndicator = null;

    /**
     * Amount type, in a coded form.
     *
     * @var string|null
     * @SerializedName("Type")
     * @Assert\NotNull()
     * @Assert\Type("string")
     * @Type("string")
     */
    protected ?string $type = null;

    /**
     * @var OBActiveOrHistoricCurrencyAndAmount8|null
     * @SerializedName("Amount")
     * @Assert\NotNull()
     * @Assert\Valid()
     * @Assert\Type("OpenAPI\Server\Model\OBActiveOrHistoricCurrencyAndAmount8")
     * @Type("OpenAPI\Server\Model\OBActiveOrHistoricCurrencyAndAmount8")
     */
    protected ?OBActiveOrHistoricCurrencyAndAmount8 $amount = null;

    /**
     * Constructor
     * @param array|null $data Associated array of property values initializing the model
     */
    public function __construct(array $data = null)
    {
        $this->creditDebitIndicator = $data['creditDebitIndicator'] ?? null;
        $this->type = $data['type'] ?? null;
        $this->amount = $data['amount'] ?? null;
    }

    /**
     * Gets creditDebitIndicator.
     *
     * @return OBCreditDebitCode0|null
     */
    public function getCreditDebitIndicator(): ?OBCreditDebitCode0
    {
        return $this->creditDebitIndicator;
    }

    /**
     * Sets creditDebitIndicator.
     *
     * @param OBCreditDebitCode0|null $creditDebitIndicator
     *
     * @return $this
     */
    public function setCreditDebitIndicator(?OBCreditDebitCode0 $creditDebitIndicator): self
    {
        $this->creditDebitIndicator = $creditDebitIndicator;

        return $this;
    }

    /**
     * Gets type.
     *
     * @return string|null
     */
    public function getType(): ?string
    {
        return $this->type;
    }

    /**
     * Sets type.
     *
     * @param string|null $type  Amount type, in a coded form.
     *
     * @return $this
     */
    public function setType(?string $type): self
    {
        $this->type = $type;

        return $this;
    }

    /**
     * Gets amount.
     *
     * @return OBActiveOrHistoricCurrencyAndAmount8|null
     */
    public function getAmount(): ?OBActiveOrHistoricCurrencyAndAmount8
    {
        return $this->amount;
    }

    /**
     * Sets amount.
     *
     * @param OBActiveOrHistoricCurrencyAndAmount8|null $amount
     *
     * @return $this
     */
    public function setAmount(?OBActiveOrHistoricCurrencyAndAmount8 $amount): self
    {
        $this->amount = $amount;

        return $this;
    }
}


