<?php
/**
 * OBTransactionCashBalance
 *
 * PHP version 8.1.1
 *
 * @category Class
 * @package  OpenAPI\Server\Model
 * @author   OpenAPI Generator team
 * @link     https://github.com/openapitools/openapi-generator
 */

/**
 * Account and Transaction API Specification
 *
 * Swagger for Account and Transaction API Specification
 *
 * The version of the OpenAPI document: 3.1.11
 * Contact: ServiceDesk@openbanking.org.uk
 * Generated by: https://github.com/openapitools/openapi-generator.git
 *
 */

/**
 * NOTE: This class is auto generated by the openapi generator program.
 * https://github.com/openapitools/openapi-generator
 * Do not edit the class manually.
 */

namespace OpenAPI\Server\Model;

use Symfony\Component\Validator\Constraints as Assert;
use JMS\Serializer\Annotation\Type;
use JMS\Serializer\Annotation\SerializedName;

/**
 * Class representing the OBTransactionCashBalance model.
 *
 * Set of elements used to define the balance as a numerical representation of the net increases and decreases in an account after a transaction entry is applied to the account.
 *
 * @package OpenAPI\Server\Model
 * @author  OpenAPI Generator team
 */

class OBTransactionCashBalance 
{
        /**
     * @var OBCreditDebitCode2|null
     * @SerializedName("CreditDebitIndicator")
     * @Assert\NotNull()
     * @Assert\Valid()
     * @Assert\Type("OpenAPI\Server\Model\OBCreditDebitCode2")
     * @Type("OpenAPI\Server\Model\OBCreditDebitCode2")
     */
    protected ?OBCreditDebitCode2 $creditDebitIndicator = null;

    /**
     * @var OBBalanceType1Code|null
     * @SerializedName("Type")
     * @Assert\NotNull()
     * @Assert\Valid()
     * @Assert\Type("OpenAPI\Server\Model\OBBalanceType1Code")
     * @Type("OpenAPI\Server\Model\OBBalanceType1Code")
     */
    protected ?OBBalanceType1Code $type = null;

    /**
     * @var OBTransactionCashBalanceAmount|null
     * @SerializedName("Amount")
     * @Assert\NotNull()
     * @Assert\Valid()
     * @Assert\Type("OpenAPI\Server\Model\OBTransactionCashBalanceAmount")
     * @Type("OpenAPI\Server\Model\OBTransactionCashBalanceAmount")
     */
    protected ?OBTransactionCashBalanceAmount $amount = null;

    /**
     * Constructor
     * @param array|null $data Associated array of property values initializing the model
     */
    public function __construct(array $data = null)
    {
        $this->creditDebitIndicator = $data['creditDebitIndicator'] ?? null;
        $this->type = $data['type'] ?? null;
        $this->amount = $data['amount'] ?? null;
    }

    /**
     * Gets creditDebitIndicator.
     *
     * @return OBCreditDebitCode2|null
     */
    public function getCreditDebitIndicator(): ?OBCreditDebitCode2
    {
        return $this->creditDebitIndicator;
    }

    /**
     * Sets creditDebitIndicator.
     *
     * @param OBCreditDebitCode2|null $creditDebitIndicator
     *
     * @return $this
     */
    public function setCreditDebitIndicator(?OBCreditDebitCode2 $creditDebitIndicator): self
    {
        $this->creditDebitIndicator = $creditDebitIndicator;

        return $this;
    }

    /**
     * Gets type.
     *
     * @return OBBalanceType1Code|null
     */
    public function getType(): ?OBBalanceType1Code
    {
        return $this->type;
    }

    /**
     * Sets type.
     *
     * @param OBBalanceType1Code|null $type
     *
     * @return $this
     */
    public function setType(?OBBalanceType1Code $type): self
    {
        $this->type = $type;

        return $this;
    }

    /**
     * Gets amount.
     *
     * @return OBTransactionCashBalanceAmount|null
     */
    public function getAmount(): ?OBTransactionCashBalanceAmount
    {
        return $this->amount;
    }

    /**
     * Sets amount.
     *
     * @param OBTransactionCashBalanceAmount|null $amount
     *
     * @return $this
     */
    public function setAmount(?OBTransactionCashBalanceAmount $amount): self
    {
        $this->amount = $amount;

        return $this;
    }
}


