<?php
/**
 * ProductDetails
 *
 * PHP version 8.1.1
 *
 * @category Class
 * @package  OpenAPI\Server\Model
 * @author   OpenAPI Generator team
 * @link     https://github.com/openapitools/openapi-generator
 */

/**
 * Account and Transaction API Specification
 *
 * Swagger for Account and Transaction API Specification
 *
 * The version of the OpenAPI document: 3.1.11
 * Contact: ServiceDesk@openbanking.org.uk
 * Generated by: https://github.com/openapitools/openapi-generator.git
 *
 */

/**
 * NOTE: This class is auto generated by the openapi generator program.
 * https://github.com/openapitools/openapi-generator
 * Do not edit the class manually.
 */

namespace OpenAPI\Server\Model;

use Symfony\Component\Validator\Constraints as Assert;
use JMS\Serializer\Annotation\Type;
use JMS\Serializer\Annotation\SerializedName;

/**
 * Class representing the ProductDetails model.
 *
 * @package OpenAPI\Server\Model
 * @author  OpenAPI Generator team
 */

class ProductDetails 
{
        /**
     * Market segmentation is a marketing term referring to the aggregating of prospective buyers into groups, or segments, that have common needs and respond similarly to a marketing action. Market segmentation enables companies to target different categories of consumers who perceive the full value of certain products and services differently from one another.  Read more: Market Segmentation http://www.investopedia.com/terms/m/marketsegmentation.asp#ixzz4gfEEalTd  With respect to BCA products, they are segmented in relation to different markets that they wish to focus on.
     *
     * @var array|null
     * @SerializedName("Segment")
     * @Assert\All({
     *   @Assert\Choice({ "ClientAccount", "Standard", "NonCommercialChaitiesClbSoc", "NonCommercialPublicAuthGovt", "Religious", "SectorSpecific", "Startup", "Switcher" })
     * })
     * @Assert\All({
     *   @Assert\Type("string")
     * })
     * @Type("array<string>")
     */
    protected ?array $segment = null;

    /**
     * The length/duration of the fee free period
     *
     * @var float|null
     * @SerializedName("FeeFreeLength")
     * @Assert\Type("float")
     * @Type("float")
     */
    protected ?float $feeFreeLength = null;

    /**
     * The unit of period (days, weeks, months etc.) of the promotional length
     *
     * @var string|null
     * @SerializedName("FeeFreeLengthPeriod")
     * @Assert\Choice({ "Day", "Half Year", "Month", "Quarter", "Week", "Year" })
     * @Assert\Type("string")
     * @Type("string")
     */
    protected ?string $feeFreeLengthPeriod = null;

    /**
     * Optional additional notes to supplement the Core product details
     *
     * @var array|null
     * @SerializedName("Notes")
     * @Assert\All({
     *   @Assert\Type("string")
     * })
     * @Type("array<string>")
     */
    protected ?array $notes = null;

    /**
     * Constructor
     * @param array|null $data Associated array of property values initializing the model
     */
    public function __construct(array $data = null)
    {
        $this->segment = $data['segment'] ?? null;
        $this->feeFreeLength = $data['feeFreeLength'] ?? null;
        $this->feeFreeLengthPeriod = $data['feeFreeLengthPeriod'] ?? null;
        $this->notes = $data['notes'] ?? null;
    }

    /**
     * Gets segment.
     *
     * @return array|null
     */
    public function getSegment(): ?array
    {
        return $this->segment;
    }

    /**
     * Sets segment.
     *
     * @param array|null $segment  Market segmentation is a marketing term referring to the aggregating of prospective buyers into groups, or segments, that have common needs and respond similarly to a marketing action. Market segmentation enables companies to target different categories of consumers who perceive the full value of certain products and services differently from one another.  Read more: Market Segmentation http://www.investopedia.com/terms/m/marketsegmentation.asp#ixzz4gfEEalTd  With respect to BCA products, they are segmented in relation to different markets that they wish to focus on.
     *
     * @return $this
     */
    public function setSegment(?array $segment = null): self
    {
        $this->segment = $segment;

        return $this;
    }

    /**
     * Gets feeFreeLength.
     *
     * @return float|null
     */
    public function getFeeFreeLength(): ?float
    {
        return $this->feeFreeLength;
    }

    /**
     * Sets feeFreeLength.
     *
     * @param float|null $feeFreeLength  The length/duration of the fee free period
     *
     * @return $this
     */
    public function setFeeFreeLength(?float $feeFreeLength = null): self
    {
        $this->feeFreeLength = $feeFreeLength;

        return $this;
    }

    /**
     * Gets feeFreeLengthPeriod.
     *
     * @return string|null
     */
    public function getFeeFreeLengthPeriod(): ?string
    {
        return $this->feeFreeLengthPeriod;
    }

    /**
     * Sets feeFreeLengthPeriod.
     *
     * @param string|null $feeFreeLengthPeriod  The unit of period (days, weeks, months etc.) of the promotional length
     *
     * @return $this
     */
    public function setFeeFreeLengthPeriod(?string $feeFreeLengthPeriod = null): self
    {
        $this->feeFreeLengthPeriod = $feeFreeLengthPeriod;

        return $this;
    }

    /**
     * Gets notes.
     *
     * @return array|null
     */
    public function getNotes(): ?array
    {
        return $this->notes;
    }

    /**
     * Sets notes.
     *
     * @param array|null $notes  Optional additional notes to supplement the Core product details
     *
     * @return $this
     */
    public function setNotes(?array $notes = null): self
    {
        $this->notes = $notes;

        return $this;
    }
}


