<?php
/**
 * FeeApplicableRangeTest
 *
 * PHP version 8.1.1
 *
 * @category Class
 * @package  OpenAPI\Server\Tests\Model
 * @author   openapi-generator contributors
 * @link     https://github.com/openapitools/openapi-generator
 */

/**
 * Account and Transaction API Specification
 *
 * Swagger for Account and Transaction API Specification
 *
 * The version of the OpenAPI document: 3.1.11
 * Contact: ServiceDesk@openbanking.org.uk
 * Generated by: https://github.com/openapitools/openapi-generator.git
 *
 */

/**
 * NOTE: This class is auto generated by the openapi generator program.
 * https://github.com/openapitools/openapi-generator
 * Please update the test case below to test the model.
 */

namespace OpenAPI\Server\Model;

use PHPUnit\Framework\MockObject\MockObject;
use PHPUnit\Framework\TestCase;

/**
 * FeeApplicableRangeTest Class Doc Comment
 *
 * @category    Class
 * @description Range or amounts or rates for which the fee/charge applies
 * @package     OpenAPI\Server\Tests\Model
 * @author      openapi-generator contributors
 * @link        https://github.com/openapitools/openapi-generator
 * @coversDefaultClass \OpenAPI\Server\Model\FeeApplicableRange
 */
class FeeApplicableRangeTest extends TestCase
{
    protected FeeApplicableRange|MockObject $object;

    /**
     * Setup before running any test case
     */
    public static function setUpBeforeClass(): void
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp(): void
    {
         $this->object = $this->getMockBuilder(FeeApplicableRange::class)->getMockForAbstractClass();
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown(): void
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass(): void
    {
    }

    /**
     * @group integration
     * @small
     */
    public function testTestClassExists(): void
    {
        $this->assertTrue(class_exists(FeeApplicableRange::class));
        $this->assertInstanceOf(FeeApplicableRange::class, $this->object);
    }

    /**
     * Test attribute "minimumAmount"
     *
     * @group unit
     * @small
     */
    public function testPropertyMinimumAmount(): void
    {
        $this->markTestSkipped('Test for property minimumAmount not implemented');
    }

    /**
     * Test attribute "maximumAmount"
     *
     * @group unit
     * @small
     */
    public function testPropertyMaximumAmount(): void
    {
        $this->markTestSkipped('Test for property maximumAmount not implemented');
    }

    /**
     * Test attribute "minimumRate"
     *
     * @group unit
     * @small
     */
    public function testPropertyMinimumRate(): void
    {
        $this->markTestSkipped('Test for property minimumRate not implemented');
    }

    /**
     * Test attribute "maximumRate"
     *
     * @group unit
     * @small
     */
    public function testPropertyMaximumRate(): void
    {
        $this->markTestSkipped('Test for property maximumRate not implemented');
    }
}
