<?php
/**
 * LinksTest
 *
 * PHP version 8.1.1
 *
 * @category Class
 * @package  OpenAPI\Server\Tests\Model
 * @author   openapi-generator contributors
 * @link     https://github.com/openapitools/openapi-generator
 */

/**
 * Account and Transaction API Specification
 *
 * Swagger for Account and Transaction API Specification
 *
 * The version of the OpenAPI document: 3.1.11
 * Contact: ServiceDesk@openbanking.org.uk
 * Generated by: https://github.com/openapitools/openapi-generator.git
 *
 */

/**
 * NOTE: This class is auto generated by the openapi generator program.
 * https://github.com/openapitools/openapi-generator
 * Please update the test case below to test the model.
 */

namespace OpenAPI\Server\Model;

use PHPUnit\Framework\MockObject\MockObject;
use PHPUnit\Framework\TestCase;

/**
 * LinksTest Class Doc Comment
 *
 * @category    Class
 * @description Links relevant to the payload
 * @package     OpenAPI\Server\Tests\Model
 * @author      openapi-generator contributors
 * @link        https://github.com/openapitools/openapi-generator
 * @coversDefaultClass \OpenAPI\Server\Model\Links
 */
class LinksTest extends TestCase
{
    protected Links|MockObject $object;

    /**
     * Setup before running any test case
     */
    public static function setUpBeforeClass(): void
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp(): void
    {
         $this->object = $this->getMockBuilder(Links::class)->getMockForAbstractClass();
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown(): void
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass(): void
    {
    }

    /**
     * @group integration
     * @small
     */
    public function testTestClassExists(): void
    {
        $this->assertTrue(class_exists(Links::class));
        $this->assertInstanceOf(Links::class, $this->object);
    }

    /**
     * Test attribute "self"
     *
     * @group unit
     * @small
     */
    public function testPropertySelf(): void
    {
        $this->markTestSkipped('Test for property self not implemented');
    }

    /**
     * Test attribute "first"
     *
     * @group unit
     * @small
     */
    public function testPropertyFirst(): void
    {
        $this->markTestSkipped('Test for property first not implemented');
    }

    /**
     * Test attribute "prev"
     *
     * @group unit
     * @small
     */
    public function testPropertyPrev(): void
    {
        $this->markTestSkipped('Test for property prev not implemented');
    }

    /**
     * Test attribute "next"
     *
     * @group unit
     * @small
     */
    public function testPropertyNext(): void
    {
        $this->markTestSkipped('Test for property next not implemented');
    }

    /**
     * Test attribute "last"
     *
     * @group unit
     * @small
     */
    public function testPropertyLast(): void
    {
        $this->markTestSkipped('Test for property last not implemented');
    }
}
