<?php
/**
 * OBBeneficiary5DetailTest
 *
 * PHP version 8.1.1
 *
 * @category Class
 * @package  OpenAPI\Server\Tests\Model
 * @author   openapi-generator contributors
 * @link     https://github.com/openapitools/openapi-generator
 */

/**
 * Account and Transaction API Specification
 *
 * Swagger for Account and Transaction API Specification
 *
 * The version of the OpenAPI document: 3.1.11
 * Contact: ServiceDesk@openbanking.org.uk
 * Generated by: https://github.com/openapitools/openapi-generator.git
 *
 */

/**
 * NOTE: This class is auto generated by the openapi generator program.
 * https://github.com/openapitools/openapi-generator
 * Please update the test case below to test the model.
 */

namespace OpenAPI\Server\Model;

use PHPUnit\Framework\MockObject\MockObject;
use PHPUnit\Framework\TestCase;

/**
 * OBBeneficiary5DetailTest Class Doc Comment
 *
 * @category    Class
 * @description OBBeneficiary5Detail
 * @package     OpenAPI\Server\Tests\Model
 * @author      openapi-generator contributors
 * @link        https://github.com/openapitools/openapi-generator
 * @coversDefaultClass \OpenAPI\Server\Model\OBBeneficiary5Detail
 */
class OBBeneficiary5DetailTest extends TestCase
{
    protected OBBeneficiary5Detail|MockObject $object;

    /**
     * Setup before running any test case
     */
    public static function setUpBeforeClass(): void
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp(): void
    {
         $this->object = $this->getMockBuilder(OBBeneficiary5Detail::class)->getMockForAbstractClass();
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown(): void
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass(): void
    {
    }

    /**
     * @group integration
     * @small
     */
    public function testTestClassExists(): void
    {
        $this->assertTrue(class_exists(OBBeneficiary5Detail::class));
        $this->assertInstanceOf(OBBeneficiary5Detail::class, $this->object);
    }

    /**
     * Test attribute "accountId"
     *
     * @group unit
     * @small
     */
    public function testPropertyAccountId(): void
    {
        $this->markTestSkipped('Test for property accountId not implemented');
    }

    /**
     * Test attribute "beneficiaryId"
     *
     * @group unit
     * @small
     */
    public function testPropertyBeneficiaryId(): void
    {
        $this->markTestSkipped('Test for property beneficiaryId not implemented');
    }

    /**
     * Test attribute "beneficiaryType"
     *
     * @group unit
     * @small
     */
    public function testPropertyBeneficiaryType(): void
    {
        $this->markTestSkipped('Test for property beneficiaryType not implemented');
    }

    /**
     * Test attribute "reference"
     *
     * @group unit
     * @small
     */
    public function testPropertyReference(): void
    {
        $this->markTestSkipped('Test for property reference not implemented');
    }

    /**
     * Test attribute "supplementaryData"
     *
     * @group unit
     * @small
     */
    public function testPropertySupplementaryData(): void
    {
        $this->markTestSkipped('Test for property supplementaryData not implemented');
    }

    /**
     * Test attribute "creditorAgent"
     *
     * @group unit
     * @small
     */
    public function testPropertyCreditorAgent(): void
    {
        $this->markTestSkipped('Test for property creditorAgent not implemented');
    }

    /**
     * Test attribute "creditorAccount"
     *
     * @group unit
     * @small
     */
    public function testPropertyCreditorAccount(): void
    {
        $this->markTestSkipped('Test for property creditorAccount not implemented');
    }
}
