<?php
/**
 * OBReadProduct2DataProductInnerOtherProductTypeLoanInterestLoanInterestTierBandSetInnerLoanInterestTierBandInnerTest
 *
 * PHP version 8.1.1
 *
 * @category Class
 * @package  OpenAPI\Server\Tests\Model
 * @author   openapi-generator contributors
 * @link     https://github.com/openapitools/openapi-generator
 */

/**
 * Account and Transaction API Specification
 *
 * Swagger for Account and Transaction API Specification
 *
 * The version of the OpenAPI document: 3.1.11
 * Contact: ServiceDesk@openbanking.org.uk
 * Generated by: https://github.com/openapitools/openapi-generator.git
 *
 */

/**
 * NOTE: This class is auto generated by the openapi generator program.
 * https://github.com/openapitools/openapi-generator
 * Please update the test case below to test the model.
 */

namespace OpenAPI\Server\Model;

use PHPUnit\Framework\MockObject\MockObject;
use PHPUnit\Framework\TestCase;

/**
 * OBReadProduct2DataProductInnerOtherProductTypeLoanInterestLoanInterestTierBandSetInnerLoanInterestTierBandInnerTest Class Doc Comment
 *
 * @category    Class
 * @description Tier Band Details
 * @package     OpenAPI\Server\Tests\Model
 * @author      openapi-generator contributors
 * @link        https://github.com/openapitools/openapi-generator
 * @coversDefaultClass \OpenAPI\Server\Model\OBReadProduct2DataProductInnerOtherProductTypeLoanInterestLoanInterestTierBandSetInnerLoanInterestTierBandInner
 */
class OBReadProduct2DataProductInnerOtherProductTypeLoanInterestLoanInterestTierBandSetInnerLoanInterestTierBandInnerTest extends TestCase
{
    protected OBReadProduct2DataProductInnerOtherProductTypeLoanInterestLoanInterestTierBandSetInnerLoanInterestTierBandInner|MockObject $object;

    /**
     * Setup before running any test case
     */
    public static function setUpBeforeClass(): void
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp(): void
    {
         $this->object = $this->getMockBuilder(OBReadProduct2DataProductInnerOtherProductTypeLoanInterestLoanInterestTierBandSetInnerLoanInterestTierBandInner::class)->getMockForAbstractClass();
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown(): void
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass(): void
    {
    }

    /**
     * @group integration
     * @small
     */
    public function testTestClassExists(): void
    {
        $this->assertTrue(class_exists(OBReadProduct2DataProductInnerOtherProductTypeLoanInterestLoanInterestTierBandSetInnerLoanInterestTierBandInner::class));
        $this->assertInstanceOf(OBReadProduct2DataProductInnerOtherProductTypeLoanInterestLoanInterestTierBandSetInnerLoanInterestTierBandInner::class, $this->object);
    }

    /**
     * Test attribute "identification"
     *
     * @group unit
     * @small
     */
    public function testPropertyIdentification(): void
    {
        $this->markTestSkipped('Test for property identification not implemented');
    }

    /**
     * Test attribute "tierValueMinimum"
     *
     * @group unit
     * @small
     */
    public function testPropertyTierValueMinimum(): void
    {
        $this->markTestSkipped('Test for property tierValueMinimum not implemented');
    }

    /**
     * Test attribute "tierValueMaximum"
     *
     * @group unit
     * @small
     */
    public function testPropertyTierValueMaximum(): void
    {
        $this->markTestSkipped('Test for property tierValueMaximum not implemented');
    }

    /**
     * Test attribute "tierValueMinTerm"
     *
     * @group unit
     * @small
     */
    public function testPropertyTierValueMinTerm(): void
    {
        $this->markTestSkipped('Test for property tierValueMinTerm not implemented');
    }

    /**
     * Test attribute "minTermPeriod"
     *
     * @group unit
     * @small
     */
    public function testPropertyMinTermPeriod(): void
    {
        $this->markTestSkipped('Test for property minTermPeriod not implemented');
    }

    /**
     * Test attribute "tierValueMaxTerm"
     *
     * @group unit
     * @small
     */
    public function testPropertyTierValueMaxTerm(): void
    {
        $this->markTestSkipped('Test for property tierValueMaxTerm not implemented');
    }

    /**
     * Test attribute "maxTermPeriod"
     *
     * @group unit
     * @small
     */
    public function testPropertyMaxTermPeriod(): void
    {
        $this->markTestSkipped('Test for property maxTermPeriod not implemented');
    }

    /**
     * Test attribute "fixedVariableInterestRateType"
     *
     * @group unit
     * @small
     */
    public function testPropertyFixedVariableInterestRateType(): void
    {
        $this->markTestSkipped('Test for property fixedVariableInterestRateType not implemented');
    }

    /**
     * Test attribute "repAPR"
     *
     * @group unit
     * @small
     */
    public function testPropertyRepAPR(): void
    {
        $this->markTestSkipped('Test for property repAPR not implemented');
    }

    /**
     * Test attribute "loanProviderInterestRateType"
     *
     * @group unit
     * @small
     */
    public function testPropertyLoanProviderInterestRateType(): void
    {
        $this->markTestSkipped('Test for property loanProviderInterestRateType not implemented');
    }

    /**
     * Test attribute "loanProviderInterestRate"
     *
     * @group unit
     * @small
     */
    public function testPropertyLoanProviderInterestRate(): void
    {
        $this->markTestSkipped('Test for property loanProviderInterestRate not implemented');
    }

    /**
     * Test attribute "notes"
     *
     * @group unit
     * @small
     */
    public function testPropertyNotes(): void
    {
        $this->markTestSkipped('Test for property notes not implemented');
    }

    /**
     * Test attribute "otherLoanProviderInterestRateType"
     *
     * @group unit
     * @small
     */
    public function testPropertyOtherLoanProviderInterestRateType(): void
    {
        $this->markTestSkipped('Test for property otherLoanProviderInterestRateType not implemented');
    }

    /**
     * Test attribute "loanInterestFeesCharges"
     *
     * @group unit
     * @small
     */
    public function testPropertyLoanInterestFeesCharges(): void
    {
        $this->markTestSkipped('Test for property loanInterestFeesCharges not implemented');
    }
}
