<?php
/**
 * OBStatement2DetailTest
 *
 * PHP version 8.1.1
 *
 * @category Class
 * @package  OpenAPI\Server\Tests\Model
 * @author   openapi-generator contributors
 * @link     https://github.com/openapitools/openapi-generator
 */

/**
 * Account and Transaction API Specification
 *
 * Swagger for Account and Transaction API Specification
 *
 * The version of the OpenAPI document: 3.1.11
 * Contact: ServiceDesk@openbanking.org.uk
 * Generated by: https://github.com/openapitools/openapi-generator.git
 *
 */

/**
 * NOTE: This class is auto generated by the openapi generator program.
 * https://github.com/openapitools/openapi-generator
 * Please update the test case below to test the model.
 */

namespace OpenAPI\Server\Model;

use PHPUnit\Framework\MockObject\MockObject;
use PHPUnit\Framework\TestCase;

/**
 * OBStatement2DetailTest Class Doc Comment
 *
 * @category    Class
 * @description Provides further details on a statement resource.
 * @package     OpenAPI\Server\Tests\Model
 * @author      openapi-generator contributors
 * @link        https://github.com/openapitools/openapi-generator
 * @coversDefaultClass \OpenAPI\Server\Model\OBStatement2Detail
 */
class OBStatement2DetailTest extends TestCase
{
    protected OBStatement2Detail|MockObject $object;

    /**
     * Setup before running any test case
     */
    public static function setUpBeforeClass(): void
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp(): void
    {
         $this->object = $this->getMockBuilder(OBStatement2Detail::class)->getMockForAbstractClass();
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown(): void
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass(): void
    {
    }

    /**
     * @group integration
     * @small
     */
    public function testTestClassExists(): void
    {
        $this->assertTrue(class_exists(OBStatement2Detail::class));
        $this->assertInstanceOf(OBStatement2Detail::class, $this->object);
    }

    /**
     * Test attribute "accountId"
     *
     * @group unit
     * @small
     */
    public function testPropertyAccountId(): void
    {
        $this->markTestSkipped('Test for property accountId not implemented');
    }

    /**
     * Test attribute "statementId"
     *
     * @group unit
     * @small
     */
    public function testPropertyStatementId(): void
    {
        $this->markTestSkipped('Test for property statementId not implemented');
    }

    /**
     * Test attribute "statementReference"
     *
     * @group unit
     * @small
     */
    public function testPropertyStatementReference(): void
    {
        $this->markTestSkipped('Test for property statementReference not implemented');
    }

    /**
     * Test attribute "type"
     *
     * @group unit
     * @small
     */
    public function testPropertyType(): void
    {
        $this->markTestSkipped('Test for property type not implemented');
    }

    /**
     * Test attribute "startDateTime"
     *
     * @group unit
     * @small
     */
    public function testPropertyStartDateTime(): void
    {
        $this->markTestSkipped('Test for property startDateTime not implemented');
    }

    /**
     * Test attribute "endDateTime"
     *
     * @group unit
     * @small
     */
    public function testPropertyEndDateTime(): void
    {
        $this->markTestSkipped('Test for property endDateTime not implemented');
    }

    /**
     * Test attribute "creationDateTime"
     *
     * @group unit
     * @small
     */
    public function testPropertyCreationDateTime(): void
    {
        $this->markTestSkipped('Test for property creationDateTime not implemented');
    }

    /**
     * Test attribute "statementDescription"
     *
     * @group unit
     * @small
     */
    public function testPropertyStatementDescription(): void
    {
        $this->markTestSkipped('Test for property statementDescription not implemented');
    }

    /**
     * Test attribute "statementBenefit"
     *
     * @group unit
     * @small
     */
    public function testPropertyStatementBenefit(): void
    {
        $this->markTestSkipped('Test for property statementBenefit not implemented');
    }

    /**
     * Test attribute "statementFee"
     *
     * @group unit
     * @small
     */
    public function testPropertyStatementFee(): void
    {
        $this->markTestSkipped('Test for property statementFee not implemented');
    }

    /**
     * Test attribute "statementInterest"
     *
     * @group unit
     * @small
     */
    public function testPropertyStatementInterest(): void
    {
        $this->markTestSkipped('Test for property statementInterest not implemented');
    }

    /**
     * Test attribute "statementAmount"
     *
     * @group unit
     * @small
     */
    public function testPropertyStatementAmount(): void
    {
        $this->markTestSkipped('Test for property statementAmount not implemented');
    }

    /**
     * Test attribute "statementDateTime"
     *
     * @group unit
     * @small
     */
    public function testPropertyStatementDateTime(): void
    {
        $this->markTestSkipped('Test for property statementDateTime not implemented');
    }

    /**
     * Test attribute "statementRate"
     *
     * @group unit
     * @small
     */
    public function testPropertyStatementRate(): void
    {
        $this->markTestSkipped('Test for property statementRate not implemented');
    }

    /**
     * Test attribute "statementValue"
     *
     * @group unit
     * @small
     */
    public function testPropertyStatementValue(): void
    {
        $this->markTestSkipped('Test for property statementValue not implemented');
    }
}
