<?php
/**
 * OverdraftTierBandInner1Test
 *
 * PHP version 8.1.1
 *
 * @category Class
 * @package  OpenAPI\Server\Tests\Model
 * @author   openapi-generator contributors
 * @link     https://github.com/openapitools/openapi-generator
 */

/**
 * Account and Transaction API Specification
 *
 * Swagger for Account and Transaction API Specification
 *
 * The version of the OpenAPI document: 3.1.11
 * Contact: ServiceDesk@openbanking.org.uk
 * Generated by: https://github.com/openapitools/openapi-generator.git
 *
 */

/**
 * NOTE: This class is auto generated by the openapi generator program.
 * https://github.com/openapitools/openapi-generator
 * Please update the test case below to test the model.
 */

namespace OpenAPI\Server\Model;

use PHPUnit\Framework\MockObject\MockObject;
use PHPUnit\Framework\TestCase;

/**
 * OverdraftTierBandInner1Test Class Doc Comment
 *
 * @category    Class
 * @description Provides overdraft details for a specific tier or band
 * @package     OpenAPI\Server\Tests\Model
 * @author      openapi-generator contributors
 * @link        https://github.com/openapitools/openapi-generator
 * @coversDefaultClass \OpenAPI\Server\Model\OverdraftTierBandInner1
 */
class OverdraftTierBandInner1Test extends TestCase
{
    protected OverdraftTierBandInner1|MockObject $object;

    /**
     * Setup before running any test case
     */
    public static function setUpBeforeClass(): void
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp(): void
    {
         $this->object = $this->getMockBuilder(OverdraftTierBandInner1::class)->getMockForAbstractClass();
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown(): void
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass(): void
    {
    }

    /**
     * @group integration
     * @small
     */
    public function testTestClassExists(): void
    {
        $this->assertTrue(class_exists(OverdraftTierBandInner1::class));
        $this->assertInstanceOf(OverdraftTierBandInner1::class, $this->object);
    }

    /**
     * Test attribute "identification"
     *
     * @group unit
     * @small
     */
    public function testPropertyIdentification(): void
    {
        $this->markTestSkipped('Test for property identification not implemented');
    }

    /**
     * Test attribute "tierValueMin"
     *
     * @group unit
     * @small
     */
    public function testPropertyTierValueMin(): void
    {
        $this->markTestSkipped('Test for property tierValueMin not implemented');
    }

    /**
     * Test attribute "tierValueMax"
     *
     * @group unit
     * @small
     */
    public function testPropertyTierValueMax(): void
    {
        $this->markTestSkipped('Test for property tierValueMax not implemented');
    }

    /**
     * Test attribute "overdraftInterestChargingCoverage"
     *
     * @group unit
     * @small
     */
    public function testPropertyOverdraftInterestChargingCoverage(): void
    {
        $this->markTestSkipped('Test for property overdraftInterestChargingCoverage not implemented');
    }

    /**
     * Test attribute "bankGuaranteedIndicator"
     *
     * @group unit
     * @small
     */
    public function testPropertyBankGuaranteedIndicator(): void
    {
        $this->markTestSkipped('Test for property bankGuaranteedIndicator not implemented');
    }

    /**
     * Test attribute "eAR"
     *
     * @group unit
     * @small
     */
    public function testPropertyEAR(): void
    {
        $this->markTestSkipped('Test for property eAR not implemented');
    }

    /**
     * Test attribute "representativeAPR"
     *
     * @group unit
     * @small
     */
    public function testPropertyRepresentativeAPR(): void
    {
        $this->markTestSkipped('Test for property representativeAPR not implemented');
    }

    /**
     * Test attribute "notes"
     *
     * @group unit
     * @small
     */
    public function testPropertyNotes(): void
    {
        $this->markTestSkipped('Test for property notes not implemented');
    }

    /**
     * Test attribute "overdraftFeesCharges"
     *
     * @group unit
     * @small
     */
    public function testPropertyOverdraftFeesCharges(): void
    {
        $this->markTestSkipped('Test for property overdraftFeesCharges not implemented');
    }
}
